# Build worker image (VM template)
image: Visual Studio 2015

init:
  # Fix line endings on Windows
  - git config --global core.autocrlf true
  # RDP for debugging purposes
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# What combinations to test
environment:
  access_token:
    secure: lssbt7qseyxwc46940dj
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: "12"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging

build: off

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json

